# List linters:
# go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest linters --no-config
#
# Run last version:
# go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run --fix
#
# Doc:
# https://golangci-lint.run/docs/configuration/file/

version: "2"

formatters:
  enable:
    # gci
    # gofmt
    - gofumpt
    # goimports
    # golines
    # swaggo
  settings:
    gofumpt:
      extra-rules: true

linters:
  default: all

  disable:
    - arangolint # arangoDB
    - depguard # list of acceptable packages, exclude other packages
    - dogsled # Checks assignments with too many blank identifiers (e.g. x, _, _, _, := f()).
    - err113 # do not define dynamic errors, use wrapped static errors instead
    - forbidigo
    - ginkgolinter
    - gochecknoglobals
    - gomoddirectives # directives 'replace', 'retract' and 'excludes' in go.mod
    - gomodguard # another Go module dependencies blocker, more featured than depguard
    - ireturn
    - mnd # Magic number
    - nlreturn
    - revive
    - staticcheck
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5

  settings:
    copyloopvar:
      check-alias: true

    dupl:
      threshold: 94

    errcheck:
      check-blank: false
      check-type-assertions: false

    errorlint:
      asserts: true
      comparison: true
      errorf: true

    exhaustruct:
      include: []
      exclude:
        - "Perm$"

    forbidigo:
      forbid:
        - msg: Use logger instead of fmt.Print
          pattern: ^fmt\.Print.*$
        - msg: Use logger instead of log
          pattern: ^log\..*$

    funlen:
      lines: 100
      statements: 50

    gocyclo:
      min-complexity: 10

    cyclop:
      max-complexity: 10

    gocognit:
      min-complexity: 18

    goconst:
      min-len: 2
      min-occurrences: 5

    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - captLocal
        - unnamedResult
        # - dupImport # https://github.com/go-critic/go-critic/issues/845
        # - ifElseChain
        # - octalLiteral
        - whyNoLint
      # - wrapperFunc
      # - yodaStyleExpr
      # - singleCaseSwitch # Every time this occurred in the code, there was no other way.

    godot:
      scope: declarations

    godox:
      keywords: ["TODO", "FIXME", "BUG", "HACK"]

    gosec:
      confidence: medium
      excludes:
        - G104
      severity: medium

    govet:
      enable-all: true
      settings:
        shadow:
          strict: true
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    importas:
      alias:
        - alias: errors
          pkg: github.com/pkg/errors
        - alias: ctx
          pkg: context

    lll:
      line-length: 160

    loggercheck:
      klog: true
      logr: true
      slog: true
      zap: true

    makezero:
      always: false

    misspell:
      locale: US

    nakedret:
      max-func-lines: 15

    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: false # don't require an explanation for nolint directives
      require-specific: true # require nolint directives to be specific about which linter is being skipped

    paralleltest:
      ignore-missing: false

    prealloc:
      for-loops: true
      range-loops: true
      simple: true

    predeclared:
      ignore: []

    promlinter:
      strict: false

    revive:
      enable-all-rules: true

    rowserrcheck:
      packages:
        - database/sql
        - github.com/jackc/pgx/v4

    sloglint:
      context: all

    # Align struct tags: `json:"bar" validate:"required" yml:"bar"`
    # https://golangci-lint.run/docs/linters/configuration/#tagalign
    tagalign:
      align: true
      sort: true
      strict: true

    # https://github.com/ldez/tagliatelle
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
          whatever: snake

    # https://github.com/butuzov/ireturn
    # https://golangci-lint.run/usage/linters/#ireturn
    ireturn:
      allow:
        - anon # anonymous interfaces such as: interface{Stop()}
        - error # error interface
        - stdlib # standard library interfaces
        - github.com/prometheus\/client_golang\/prometheus.Gauge
        - github.com/prometheus\/client_golang\/prometheus.Counter

    testifylint:
      disable-all: false
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - go-require
        - float-compare
        - len
        - nil-compare
        - require-error
        - suite-extra-assert-call
        - suite-thelper

    unparam:
      check-exported: false

    varnamelen:
      # The longest distance, in source lines, that is being considered a "small scope".
      # Variables used in at most this many lines will be ignored.
      # Default: 5
      max-distance: 14
      # The minimum length of a variable's name that is considered "long".
      # Variable names that are at least this long will be ignored.
      # Default: 3
      min-name-length: 2
      # Check method receivers.
      # Default: false
      check-receiver: false
      # Check named return values.
      # Default: false
      check-return: true
      # Check type parameters.
      # Default: false
      check-type-param: true
      # Ignore "ok" variables that hold the bool return value of a type assertion.
      # Default: false
      ignore-type-assert-ok: false
      # Ignore "ok" variables that hold the bool return value of a map index.
      # Default: false
      ignore-map-index-ok: false
      # Ignore "ok" variables that hold the bool return value of a channel receive.
      # Default: false
      ignore-chan-recv-ok: false
      # Optional list of variable names that should be ignored completely.
      # Default: []
      ignore-names:
        - err
        - r # request
        - w # writer
        - g # garcon
        - u # url
        - d # duration
      # Optional list of variable declarations that should be ignored completely.
      # Entries must be in one of the following forms (see below for examples):
      # - for variables, parameters, named return values, method receivers, or type parameters:
      #   <name> <type>  (<type> can also be a pointer/slice/map/chan/...)
      # - for constants: const <name>
      #
      # Default: []
      ignore-decls:
        - t testing.T
        - f *foo.Bar
        - e error
        - i int
        - const C
        - T any
        - m map[string]int

    whitespace:
      multi-if: true

    wrapcheck:
      ignore-interface-regexps:
        - ^(?i)error$
      ignore-package-globs:
        - errors/*
        - fmt/*
      ignore-sigs:
        - errors.New(
        - errors.New(
        - fmt.Errorf(

run:
  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1
  # which dirs to skip: they won't be analyzed;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but next dirs are always skipped independently
  # from this option's value:
  #     vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  go: "1.25"
  timeout: 5m
